default: &default
  dispatchers:
    - polling_interval: .1
      batch_size: 500
  workers:
    - queues: mef
      # We are constrained by MeF to 5 concurrent connections, so we use a limit of 5 single-threaded workers
      threads: 1
      processes: 5
      polling_interval: 0.1
    - queues: webhook_callbacks
      # We want our callbacks to not be blocked by each other, but we know they are threadsafe so we use a multi-threaded
      # worker with the same number of threads as there are mef queue workers (in case they all trigger webhooks simultaneously)
      threads: 5
      processes: 1
      polling_interval: 0.1

development:
  <<: *default

test:
  <<: *default

demo:
  <<: *default

production:
  <<: *default
