name: Deploy to AWS Demo

on:
  push:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    uses: ./.github/workflows/ci.yml
  deploy:
    name: deploy
    needs: ["tests"]
    environment: demo
    runs-on: ubuntu-latest
    env:
      ECR_REPOSITORY: efiler-api-demo-web
      IMAGE_TAG: ${{ github.sha }}
    steps:
      - run: echo 'Tests passed.'

      - run: echo 'Starting the staging deploy'

      - name: Check out code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-east-1

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      - name: Build and push Docker image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          printf "${{ secrets.GYR_EFILER_RELEASES_AWS_ACCESS_KEY_ID  }}" >> ${{ github.workspace }}/GYR_EFILER_RELEASES_AWS_ACCESS_KEY_ID
          printf "${{ secrets.GYR_EFILER_RELEASES_AWS_SECRET_ACCESS_KEY  }}" >> ${{ github.workspace }}/GYR_EFILER_RELEASES_AWS_SECRET_ACCESS_KEY
          printf "${{ secrets.RAILS_SECRET_KEY_BASE  }}" >> ${{ github.workspace }}/RAILS_SECRET_KEY_BASE
          docker build --secret id=GYR_EFILER_RELEASES_AWS_ACCESS_KEY_ID,src=${{ github.workspace }}/GYR_EFILER_RELEASES_AWS_ACCESS_KEY_ID --secret id=GYR_EFILER_RELEASES_AWS_SECRET_ACCESS_KEY,src=${{ github.workspace }}/GYR_EFILER_RELEASES_AWS_SECRET_ACCESS_KEY --secret id=SECRET_KEY_BASE,src=${{ github.workspace }}/RAILS_SECRET_KEY_BASE -t 669097061340.dkr.ecr.us-east-1.amazonaws.com/efiler-api-demo-web:${{env.IMAGE_TAG}} --platform linux/amd64 .
          docker push 669097061340.dkr.ecr.us-east-1.amazonaws.com/efiler-api-demo-web:${{env.IMAGE_TAG}}

      - name: Update SSM Version Parameter
        run: |
          echo "tag:$IMAGE_TAG"
          aws ssm put-parameter \
            --name  /efiler-api/demo/web/version \
            --value "$IMAGE_TAG" \
            --overwrite

      - name: Trigger infrastructure deployment
        run: |
          # Set the required variables
          repo_owner="codeforamerica"
          repo_name="tax-benefits-backend"
          event_type="deploy"
          environment="efiler-api-demo"
          config="demo.efilerapi.org"
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.DEPLOY_PAT }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/$repo_owner/$repo_name/dispatches \
            -d "{\"event_type\": \"$event_type\", \"client_payload\": {\"environment\": \"$environment\", \"config\": \"$config\"}}"

      - name: Notify deploy failure on Slack
        uses: 8398a7/action-slack@v3
        if: failure()
        with:
          text: "<!subteam^S06P99RGJDS> E-filer demo deploy ${{ job.status }} :angry_smiling_crying_sweating_face:"
          status: ${{ job.status }}
          fields: message,commit,author,workflow,took
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}